CREATE TABLE Geek
( Id INTEGER,
nom VARCHAR(32) NOT NULL,
prenom VARCHAR(32) NOT NULL,
sexe VARCHAR(1) NOT NULL,
age INTEGER,
email VARCHAR(255),
centreInterets VARCHAR(255),
gravatar VARCHAR(255),
PRIMARY KEY (Id))
